### ISSUE TITLE
Merging repositories for team project  

### ISSUE THREAD

**Issue by emilyemchen** [brainhack-school2020/emilyemchen-EEGML#6]
Hi @pbellec or @surchs! 
I was curious how best to merge repositories when working in a team. Should we create a new joint repository or import each of our repositories to the team?

**Comment by surchs** [comment]
The best solution would probably be to pick one of your repositories to continue working on together. Alternatively, you could create a new team repository and work on that. You can take a look at these [instructions on how to add collaborators](https://help.github.jp/enterprise/2.11/user/articles/inviting-collaborators-to-a-personal-repository/).

also: great use of labels!

**Comment by emilyemchen** [comment]
Ok, thank you for the suggestions! We've created a [new repository](https://github.com/brainhack-school2020/abide-fmri) that we will all contribute to.
